# Generated by Django 4.0 on 2021-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
