# Generated by Django 4.0 on 2022-01-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_tb_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='user_sex',
            field=models.IntegerField(blank=True, db_column='USER_SEX', null=True),
        ),
        migrations.AddField(
            model_name='user_tb',
            name='user_tall',
            field=models.IntegerField(blank=True, db_column='USER_TALL', null=True),
        ),
    ]
