# Generated by Django 4.0 on 2021-12-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_tb_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0, null=True)),
                ('record', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_tb')),
            ],
            options={
                'db_table': 'stepCount',
            },
        ),
    ]
