# Generated by Django 4.0 on 2021-12-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedometer', '0003_alter_stepcount_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepcount',
            old_name='user_id',
            new_name='user_id_pk',
        ),
    ]
